CREATE TABLE QUESTIONS(
	QID INT NOT NULL,
	QUESTION VARCHAR(200) NOT NULL,
	PRIMARY KEY(QID),
	UNIQUE(QUESTION) );
	
CREATE TABLE ANSWERS(
	ANSWER VARCHAR(50) NOT NULL,
	QID INT NOT NULL,
	CORRECT_FLAG BIT NOT NULL,
	PRIMARY KEY(ANSWER, QID),
	FOREIGN KEY (QID) REFERENCES QUESTIONS(QID) );
	
INSERT INTO QUESTIONS VALUES ( 1, 'FILLER QUESTION  1');
INSERT INTO QUESTIONS VALUES ( 2, 'FILLER QUESTION  2');
INSERT INTO QUESTIONS VALUES ( 3, 'FILLER QUESTION  3');
INSERT INTO QUESTIONS VALUES ( 4, 'FILLER QUESTION  4');
INSERT INTO QUESTIONS VALUES ( 5, 'FILLER QUESTION  5');
INSERT INTO QUESTIONS VALUES ( 6, 'FILLER QUESTION  6');
INSERT INTO QUESTIONS VALUES ( 7, 'FILLER QUESTION  7');
INSERT INTO QUESTIONS VALUES ( 8, 'FILLER QUESTION  8');
INSERT INTO QUESTIONS VALUES ( 9, 'FILLER QUESTION  9');
INSERT INTO QUESTIONS VALUES (10, 'FILLER QUESTION 10');
INSERT INTO QUESTIONS VALUES (11, 'FILLER QUESTION 11');
INSERT INTO QUESTIONS VALUES (12, 'FILLER QUESTION 12');
INSERT INTO QUESTIONS VALUES (13, 'FILLER QUESTION 13');
INSERT INTO QUESTIONS VALUES (14, 'FILLER QUESTION 14');
INSERT INTO QUESTIONS VALUES (15, 'FILLER QUESTION 15');
INSERT INTO QUESTIONS VALUES (16, 'FILLER QUESTION 16');
INSERT INTO QUESTIONS VALUES (17, 'FILLER QUESTION 17');
INSERT INTO QUESTIONS VALUES (18, 'FILLER QUESTION 18');
INSERT INTO QUESTIONS VALUES (19, 'FILLER QUESTION 19');
INSERT INTO QUESTIONS VALUES (20, 'FILLER QUESTION 20');
INSERT INTO QUESTIONS VALUES (21, 'FILLER QUESTION 21');
INSERT INTO QUESTIONS VALUES (22, 'FILLER QUESTION 22');
INSERT INTO QUESTIONS VALUES (23, 'FILLER QUESTION 23');
INSERT INTO QUESTIONS VALUES (24, 'FILLER QUESTION 24');
INSERT INTO QUESTIONS VALUES (25, 'FILLER QUESTION 25');

INSERT INTO ANSWERS VALUES ('A', 1, 1);
INSERT INTO ANSWERS VALUES ('B', 1, 0);
INSERT INTO ANSWERS VALUES ('C', 1, 0);
INSERT INTO ANSWERS VALUES ('D', 1, 0);

INSERT INTO ANSWERS VALUES ('A', 2, 1);
INSERT INTO ANSWERS VALUES ('B', 2, 0);
INSERT INTO ANSWERS VALUES ('C', 2, 0);
INSERT INTO ANSWERS VALUES ('D', 2, 0);

INSERT INTO ANSWERS VALUES ('A', 3, 1);
INSERT INTO ANSWERS VALUES ('B', 3, 0);
INSERT INTO ANSWERS VALUES ('C', 3, 0);
INSERT INTO ANSWERS VALUES ('D', 3, 0);

INSERT INTO ANSWERS VALUES ('A', 4, 1);
INSERT INTO ANSWERS VALUES ('B', 4, 0);
INSERT INTO ANSWERS VALUES ('C', 4, 0);
INSERT INTO ANSWERS VALUES ('D', 4, 0);

INSERT INTO ANSWERS VALUES ('A', 5, 1);
INSERT INTO ANSWERS VALUES ('B', 5, 0);
INSERT INTO ANSWERS VALUES ('C', 5, 0);
INSERT INTO ANSWERS VALUES ('D', 5, 0);

INSERT INTO ANSWERS VALUES ('A', 6, 1);
INSERT INTO ANSWERS VALUES ('B', 6, 0);
INSERT INTO ANSWERS VALUES ('C', 6, 0);
INSERT INTO ANSWERS VALUES ('D', 6, 0);

INSERT INTO ANSWERS VALUES ('A', 7, 1);
INSERT INTO ANSWERS VALUES ('B', 7, 0);
INSERT INTO ANSWERS VALUES ('C', 7, 0);
INSERT INTO ANSWERS VALUES ('D', 7, 0);

INSERT INTO ANSWERS VALUES ('A', 8, 1);
INSERT INTO ANSWERS VALUES ('B', 8, 0);
INSERT INTO ANSWERS VALUES ('C', 8, 0);
INSERT INTO ANSWERS VALUES ('D', 8, 0);

INSERT INTO ANSWERS VALUES ('A', 9, 1);
INSERT INTO ANSWERS VALUES ('B', 9, 0);
INSERT INTO ANSWERS VALUES ('C', 9, 0);
INSERT INTO ANSWERS VALUES ('D', 9, 0);

INSERT INTO ANSWERS VALUES ('A', 10, 1);
INSERT INTO ANSWERS VALUES ('B', 10, 0);
INSERT INTO ANSWERS VALUES ('C', 10, 0);
INSERT INTO ANSWERS VALUES ('D', 10, 0);

INSERT INTO ANSWERS VALUES ('A', 11, 1);
INSERT INTO ANSWERS VALUES ('B', 11, 0);
INSERT INTO ANSWERS VALUES ('C', 11, 0);
INSERT INTO ANSWERS VALUES ('D', 11, 0);

INSERT INTO ANSWERS VALUES ('A', 12, 1);
INSERT INTO ANSWERS VALUES ('B', 12, 0);
INSERT INTO ANSWERS VALUES ('C', 12, 0);
INSERT INTO ANSWERS VALUES ('D', 12, 0);

INSERT INTO ANSWERS VALUES ('A', 13, 1);
INSERT INTO ANSWERS VALUES ('B', 13, 0);
INSERT INTO ANSWERS VALUES ('C', 13, 0);
INSERT INTO ANSWERS VALUES ('D', 13, 0);

INSERT INTO ANSWERS VALUES ('A', 14, 1);
INSERT INTO ANSWERS VALUES ('B', 14, 0);
INSERT INTO ANSWERS VALUES ('C', 14, 0);
INSERT INTO ANSWERS VALUES ('D', 14, 0);

INSERT INTO ANSWERS VALUES ('A', 15, 1);
INSERT INTO ANSWERS VALUES ('B', 15, 0);
INSERT INTO ANSWERS VALUES ('C', 15, 0);
INSERT INTO ANSWERS VALUES ('D', 15, 0);

INSERT INTO ANSWERS VALUES ('A', 16, 1);
INSERT INTO ANSWERS VALUES ('B', 16, 0);
INSERT INTO ANSWERS VALUES ('C', 16, 0);
INSERT INTO ANSWERS VALUES ('D', 16, 0);

INSERT INTO ANSWERS VALUES ('A', 17, 1);
INSERT INTO ANSWERS VALUES ('B', 17, 0);
INSERT INTO ANSWERS VALUES ('C', 17, 0);
INSERT INTO ANSWERS VALUES ('D', 17, 0);

INSERT INTO ANSWERS VALUES ('A', 18, 1);
INSERT INTO ANSWERS VALUES ('B', 18, 0);
INSERT INTO ANSWERS VALUES ('C', 18, 0);
INSERT INTO ANSWERS VALUES ('D', 18, 0);

INSERT INTO ANSWERS VALUES ('A', 19, 1);
INSERT INTO ANSWERS VALUES ('B', 19, 0);
INSERT INTO ANSWERS VALUES ('C', 19, 0);
INSERT INTO ANSWERS VALUES ('D', 19, 0);

INSERT INTO ANSWERS VALUES ('A', 20, 1);
INSERT INTO ANSWERS VALUES ('B', 20, 0);
INSERT INTO ANSWERS VALUES ('C', 20, 0);
INSERT INTO ANSWERS VALUES ('D', 20, 0);

INSERT INTO ANSWERS VALUES ('A', 21, 1);
INSERT INTO ANSWERS VALUES ('B', 21, 0);
INSERT INTO ANSWERS VALUES ('C', 21, 0);
INSERT INTO ANSWERS VALUES ('D', 21, 0);

INSERT INTO ANSWERS VALUES ('A', 22, 1);
INSERT INTO ANSWERS VALUES ('B', 22, 0);
INSERT INTO ANSWERS VALUES ('C', 22, 0);
INSERT INTO ANSWERS VALUES ('D', 22, 0);

INSERT INTO ANSWERS VALUES ('A', 23, 1);
INSERT INTO ANSWERS VALUES ('B', 23, 0);
INSERT INTO ANSWERS VALUES ('C', 23, 0);
INSERT INTO ANSWERS VALUES ('D', 23, 0);

INSERT INTO ANSWERS VALUES ('A', 24, 1);
INSERT INTO ANSWERS VALUES ('B', 24, 0);
INSERT INTO ANSWERS VALUES ('C', 24, 0);
INSERT INTO ANSWERS VALUES ('D', 24, 0);

INSERT INTO ANSWERS VALUES ('A', 25, 1);
INSERT INTO ANSWERS VALUES ('B', 25, 0);
INSERT INTO ANSWERS VALUES ('C', 25, 0);
INSERT INTO ANSWERS VALUES ('D', 25, 0);